# Create/update tunnel, write config.yml, add DNS for your chosen hostnames.
# Hostnames must live in a DNS zone on the same Cloudflare account as cert.pem (.\login.ps1).
param(
    [string] $TunnelName = "pos-rfood-wholesale",
    [string] $FrontendHost = "",
    [string] $BackendHost = ""
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\_env.ps1"

$optionalCfg = Join-Path $PSScriptRoot "dns-config.ps1"
if (Test-Path -LiteralPath $optionalCfg) {
    . $optionalCfg
}

function Ensure-Hostname([string] $value, [string] $fromDefaultVar, [string] $fallback) {
    if (-not [string]::IsNullOrWhiteSpace($value)) { return $value.Trim() }
    if (-not [string]::IsNullOrWhiteSpace($fromDefaultVar)) { return $fromDefaultVar.Trim() }
    return $fallback
}

$FrontendHost = Ensure-Hostname $FrontendHost $DefaultFrontendHost "pos.rfoodinternational.com"
$BackendHost = Ensure-Hostname $BackendHost $DefaultBackendHost "pos-backend.rfoodinternational.com"

$localCert = Join-Path $Script:CloudflaredHome "cert.pem"
if (-not (Test-Path $localCert)) {
    Write-Host "No cert in project folder. Run .\login.ps1 first (browser login for the Cloudflare account that owns your DNS zone)."
    exit 1
}

Write-Host "DNS hostnames: frontend=$FrontendHost  backend=$BackendHost"

$credPath = Join-Path $Script:CloudflaredHome "tunnel-credentials.json"
# Do not merge stderr (cloudflared logs JSON warnings to stderr; errors also go there).
$createOut = & $CloudflaredExe tunnel create --credentials-file $credPath -o json $TunnelName
$createdOk = ($LASTEXITCODE -eq 0)

if ($createdOk) {
    $jsonLine = @($createOut) | Where-Object { $_.ToString().TrimStart().StartsWith('{') } | Select-Object -Last 1
    if (-not $jsonLine) { throw "tunnel create succeeded but no JSON line in output: $createOut" }
    $obj = $jsonLine.ToString() | ConvertFrom-Json
    $tunnelId = $obj.id
    if (-not $tunnelId) { $tunnelId = $obj.tunnel_id }
    if ($obj.credentials_file) { $credPath = $obj.credentials_file }
    elseif ($obj.credentialsFile) { $credPath = $obj.credentialsFile }
    $credPath = [System.IO.Path]::GetFullPath($credPath)
} else {
    Write-Host "Create failed or tunnel already exists; looking up '$TunnelName' in account..."
    $listJson = & $CloudflaredExe tunnel list -o json
    if ($LASTEXITCODE -ne 0) { throw "tunnel list failed; fix cert.pem or login with .\login.ps1" }
    $rows = $listJson | ConvertFrom-Json
    $match = $rows | Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1
    if (-not $match) {
        throw "tunnel create failed and no tunnel named '$TunnelName' was found. Run: cloudflared tunnel create --credentials-file `"$credPath`" -o json $TunnelName"
    }
    $tunnelId = $match.id
    $candidates = @(
        (Join-Path $Script:CloudflaredHome "$tunnelId.json"),
        (Join-Path $Script:CloudflaredHome "tunnel-credentials.json"),
        (Join-Path $env:USERPROFILE ".cloudflared\$tunnelId.json")
    )
    $credPath = $candidates | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
    if (-not $credPath) {
        throw "Tunnel '$TunnelName' exists (id $tunnelId) but credentials JSON not found. Copy $tunnelId.json into .cloudflared\ or delete the tunnel in Zero Trust and run .\bootstrap.ps1 again."
    }
    $credPath = [System.IO.Path]::GetFullPath($credPath)
    Write-Host "Using existing tunnel id $tunnelId credentials: $credPath"
}

$credPath = [System.IO.Path]::GetFullPath($credPath)
$canonicalCred = Join-Path $Script:CloudflaredHome "$tunnelId.json"
if ($credPath -ne $canonicalCred) {
    Copy-Item -LiteralPath $credPath -Destination $canonicalCred -Force
    $credPath = $canonicalCred
}
$credYaml = $credPath -replace '\\', '/'

$configContent = @"
tunnel: $tunnelId
credentials-file: $credYaml

ingress:
  - hostname: $FrontendHost
    service: http://127.0.0.1:7117
  - hostname: $BackendHost
    service: http://127.0.0.1:7227
  - service: http_status:404
"@

Set-Content -Path $Script:CloudflaredConfig -Value $configContent -Encoding UTF8

$state = @{
    tunnelName   = $TunnelName
    tunnelId     = $tunnelId
    frontendHost = $FrontendHost
    backendHost  = $BackendHost
    createdAt    = (Get-Date).ToString("o")
}
$state | ConvertTo-Json | Set-Content -Path $Script:TunnelState -Encoding UTF8

$frontendEnvDir = Join-Path $PSScriptRoot "..\frontend"
# Vite dev mode loads .env.development.local, not .env.tunnel.local.
$envDevLocal = Join-Path $frontendEnvDir ".env.development.local"
if (Test-Path -LiteralPath $frontendEnvDir) {
    $apiOrigin = "https://$BackendHost"
    @(
        "# Generated by cloudflare-tunnel\bootstrap.ps1 - matches tunnel ingress + DNS",
        "VITE_TUNNEL_FRONTEND_HOST=$FrontendHost",
        "VITE_TUNNEL_API_ORIGIN=$apiOrigin"
    ) | Set-Content -Path $envDevLocal -Encoding UTF8
    Write-Host "Wrote $envDevLocal for Vite dev (restart npm run dev after bootstrap)"
}

Write-Host "Wrote $($Script:CloudflaredConfig)"
Write-Host "Tunnel ID: $tunnelId"

Write-Host "Adding DNS routes (-f overwrites existing same-name records; names must be in your Cloudflare zone)..."
& $CloudflaredExe tunnel --config $Script:CloudflaredConfig route dns -f $tunnelId $FrontendHost
& $CloudflaredExe tunnel --config $Script:CloudflaredConfig route dns -f $tunnelId $BackendHost

Write-Host "Done. Start dev servers on 7117 (frontend) and 7227 (backend), then run .\run-tunnel.ps1"
